version: '3'

services:
  pipenv:
    image: fsfe/pipenv:python-3.8
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/app
    env_file:
      - .env
    working_dir: /app
